version: '3'

services:
  cafeorder-db:
    container_name: j-cafe-order-db
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=jcafe_order
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
